# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{daemonz}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Victor Costan"]
  s.date = %q{2010-02-06}
  s.email = %q{victor@costan.us}
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    "MIT-LICENSE",
     "README.textile",
     "Rakefile",
     "VERSION",
     "config_template.yml",
     "daemonz.gemspec",
     "init.rb",
     "lib/daemonz.rb",
     "lib/daemonz/config.rb",
     "lib/daemonz/engine.rb",
     "lib/daemonz/killer.rb",
     "lib/daemonz/logging.rb",
     "lib/daemonz/manage.rb",
     "lib/daemonz/master.rb",
     "lib/daemonz/process.rb",
     "lib/daemonz/railtie.rb",
     "lib/generators/config/config_generator.rb",
     "lib/generators/config/templates/config.yml",
     "lib/generators/config/templates/prepackaged/ferret.yml",
     "lib/generators/config/templates/prepackaged/starling.yml",
     "lib/generators/daemon/daemon_generator.rb",
     "lib/generators/daemon/templates/config.yml",
     "lib/generators/daemon/templates/daemon.rb.erb",
     "lib/generators/daemon/templates/integration_test.rb.erb",
     "lib/rails/install.rb",
     "lib/tasks/daemonz_tasks.rake"
  ]
  s.homepage = %q{http://github.com/costan/daemonz}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Automatically starts and stops the daemons in a Rails application}
  s.test_files = [
    "test/daemonz_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

